services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample_rails_development # データベース名を一致させる
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/sample_rails
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - MYSQL_USER=user # 必要な環境変数を追加
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
      - MYSQL_DATABASE=sample_rails_development

volumes:
  mysql_volume:
